project:
  type: website
  output-dir: docs

website:
  title: "Data Hub"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: reportDraft.qmd 
        text: Bessette-Sinclair Report
      - href: hubstart.qmd
        text: Data Hub
      - href: nets_project.qmd
        text: NETS Project

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



