project:
  type: website

website:
  title: "Test2"
  navbar:
    left: #This is just how you link everything. The href is the file it links to, and the text is what displays on the site.
      #- about.qmd #This is vestigial. 
      - href: index.qmd
        text: Home
      - href: datahubstart.qmd
        text: Data Hub
      - href: reportDraft.qmd #you can use this to link to a separate pg, basically
        text: Draft of Bessett-Sinclair Report
      - href: Quarto Resource.qmd
        text: Quarto Resources 
      



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



