project:
  type: website

website:
  title: "Data Hub"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: reportDraft.qmd #you can use this to link to a separate pg, basically
        text: Bessett-Sinclair Report
      - href: Quarto Resource.qmd
        text: Quarto Resources 
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



