project:
  type: website

website:
  title: "Test2"
  navbar:
    left:
      - href: index.qmd #you can use this to link to a separate pg, basically
        text: Home
      #- about.qmd #This is vestigial. 
      - href: section.qmd
        text: Test of Sections
      - href: map.qmd
        text: Map in Progress
      - href: workingmap.qmd
        text: Working Map
      - href: exact_penguin.qmd
        text: Exact Copy of Penguin Site
      - href: reportDraft.qmd #you can use this to link to a separate pg, basically
        text: Draft of Bessett-Sinclair Report
      - href: render_test.qmd
        text: Render Test
      - href: kosmontDraft.qmd
        text: Kosmont Draft
      - href: cities.qmd
      - text: City Data Project
      - href: Calabasas Demographic Data.qmd
        text: Test City Demographic Data 
      



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



