project:
  type: website
  output-dir: docs

website:
  title: "Data Hub"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: reportDraft.qmd 
        text: Bessett-Sinclair Report
      - href: Quarto Resource.qmd
        text: Quarto Resources 
      - href: hubstart.qmd
        text: Data Hub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



