---
title: "Reporting on the bill length of penguins"
author: "Myles Mitchell & Parisa Gregg"
date: "14 December 2022"
format: html
execute:
  echo: false
  enabled: true
  cache: true
jupyter: python3
editor:
  render-on-save: true #hm, kinda 100% forgot what this meant.... 
  
---

The goal here is to copy everything from a [site](https://www.jumpingrivers.com/blog/quarto-for-python-users/) where a bunch of graphs worked. Unfortunately, thus far, it has not worked. 

Currently, the goal is to use this to test the Plotly rendering, so debugging, basically. 


## Abstract

Prepare yourself for a life-changing article about penguins...

## Introduction

[Penguins](https://en.wikipedia.org/wiki/Penguin) are a family
(**Spheniscidae**) of aquatic flightless
[birds](https://en.wikipedia.org/wiki/Bird) that live primarily in the
[Southern Hemisphere](https://en.wikipedia.org/wiki/Southern_Hemisphere).
Their diet consists of:

- Krill
- Fish
- Squid
- More fish

There are 18 species of penguin, including:

1. Macaroni penguin (*Eudyptes chrysolophus*)
2. Chinstrap penguin (*Pygoscelis antarcticus*)
3. Gentoo penguin (*Pygoscelis papua*)

## Methods

To determine whether a higher body mass implies a longer bill, we loaded a
penguins dataset using pandas:

```{python}
import pandas as pd

data = pd.read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-28/penguins.csv'
)
data.head()
```

## Results

The figure below shows the bill length plotted as a function of the body mass
for three species across a 3-year period.

## Plotly

## NumPy
```{python}
import plotly.io as pio #Iirc Amy added this part to test if it was render
pio.renderers.default = "notebook"
import plotly.express as px
pio.renderers.default = "browser"
import plotly.graph_objects as go # or plotly.express 
import plotly.graph_objects as go
from IPython.display import Image
import numpy as np
#| eval: false
import plotly.express as px
#| eval: false
EXPORT_PLOTLY = False
fig = None # Define None to prevent code errors

def export_plotly(fig, filepath: str):
    if EXPORT_PLOTLY:
        fig.write_json(filepath)

gapminder = px.data.gapminder()
gapminder2007 = gapminder.query("year == 2007")
fig = px.scatter(gapminder2007, 
                 x="gdpPercap", y="lifeExp", color="continent", 
                 size="pop", size_max=60,
                 hover_name="country")
fig.show()
```


## NumPy

## Plotly

```{python}

```