<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Joseph M. Bessette">
<meta name="author" content="J. Andrew Sinclair">
<meta name="dcterms.date" content="2022-12-14">

<title>How Many Americans Support the Death Penalty? – Test2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ddd961a2510921635943dfbbd19534c4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Test2</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./section.html"> 
<span class="menu-text">Test of Sections</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./map.html"> 
<span class="menu-text">Map in Progress</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./penguin_test.html"> 
<span class="menu-text">Penguin Graphs in Progress</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./workingmap.html"> 
<span class="menu-text">Working Map</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./exact_penguin.html"> 
<span class="menu-text">Exact Copy of Penguin Site</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./reportDraft.html" aria-current="page"> 
<span class="menu-text">Draft of Bessett-Sinclair Report</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./render_test.html"> 
<span class="menu-text">Render Test</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">How Many Americans Support the Death Penalty?</h1>
            <p class="subtitle lead">Results of National Surveys in 2019 and 2020</p>
                      </div>
  </div>
    
  <div class="quarto-title-meta-author">
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-heading">Affiliation</div>
    
      <div class="quarto-title-meta-contents">
      <p class="author">Joseph M. Bessette </p>
    </div>
    <div class="quarto-title-meta-contents">
          <p class="affiliation">
              Claremont McKenna College
            </p>
        </div>
      <div class="quarto-title-meta-contents">
      <p class="author">J. Andrew Sinclair </p>
    </div>
    <div class="quarto-title-meta-contents">
          <p class="affiliation">
              Claremont McKenna College
            </p>
        </div>
    </div>

  <div class="quarto-title-meta">

        
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">December 14, 2022</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#survey-design" id="toc-survey-design" class="nav-link" data-scroll-target="#survey-design">Survey Design</a></li>
  <li><a href="#general-support-for-the-death-penalty" id="toc-general-support-for-the-death-penalty" class="nav-link" data-scroll-target="#general-support-for-the-death-penalty">General support for the death penalty</a></li>
  <li><a href="#impact-of-political-and-demographic-characteristics" id="toc-impact-of-political-and-demographic-characteristics" class="nav-link" data-scroll-target="#impact-of-political-and-demographic-characteristics">Impact of political and demographic characteristics</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Do Americans favor the death penalty for the crime of murder? According to Gallup and the Pew Research Center, two major polling organizations that regularly ask Americans this question and whose findings are widely publicized, public support ranges between 55% (Gallup, September-October, 2020) and 60% (Pew, April 2021).<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> These findings are generally accepted as an accurate gauge of current public attitudes: a clear majority in favor of the death penalty for murder but well below the modern peak of 78-80% in the mid-1990s.</p>
<p>Both Gallup and Pew ask a very generic question. Gallup asks, “Are you in favor of the death penalty for a person convicted of murder?” Although Pew gives more options to measure level of support or opposition, its question is otherwise nearly identical: “Do you strongly favor, favor, oppose or strongly oppose the death penalty for persons convicted of murder?” Most other polling organizations that have measured public opinion in the United States on the death penalty in recent decades have asked essentially the same question. One problem is that these questions do not distinguish between most murders – or, what we might call the “typical” or ”average” murder — and the specific kinds of aggravated murders that make a killer eligible for the death penalty in the 27 American states with capital punishment.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> Someone, for example, might oppose the death penalty for most murders but support it for, say, raping and murdering a child, or killing people by setting off a bomb in a public place, or killing someone after intentionally torturing the victim. How should such a person respond when asked whether he or she favors the death penalty for “a person convicted of murder”? This person might answer “no” to the generic question — and thus be counted as a death penalty opponent — even though he or she would support executing some murderers. A second problem is that the question does not allow respondents to distinguish between an abstract preference for the death penalty in some circumstances and the retention or adoption of the death penalty as actual public policy. Someone who approves of the death penalty in principle might answer “no” to the generic question because they interpret the question as asking about whether their state should have the death penalty – a policy they might oppose because of concerns about cost, mistakes, or discrimination.</p>
<p>Although polling organizations occasionally ask Americans whether they support the death penalty for a particular offender — such as Timothy McVeigh, who killed 168 in the 1995 bombing of the federal building in Oklahoma City and who was executed in 2001 (Gallup reported that 81% approved) — we can find no record in the past three decades of a national survey that polled Americans on their support for the death penalty for a variety of specific types of aggravated murder.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> To fill this gap in our knowledge of American public opinion on capital punishment, we devised a series of questions on the death penalty that were included in two national surveys (on several distinct topics) of approximately 5000 registered voters. The surveys were conducted online by YouGov in June of 2019.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
</section>
<section id="survey-design" class="level2">
<h2 class="anchored" data-anchor-id="survey-design">Survey Design</h2>
<p>The first survey began the section on capital punishment by alerting respondents that we would be asking about the death penalty for “different kinds of aggravated murders,” indicating that they could skip these questions: 92% did not. We then asked whether the respondent “support[ed] the death penalty for the crime of murder” and gave three optional responses: 1. “I support the death penalty for most or all types of murder.” 2. “I support the death penalty only for the most aggravated murders.” 3. “I oppose the death penalty for most or all types of murder.”</p>
<p>In our view, these options rectified the deficiency in the Gallup/Pew generic question because they allowed us to distinguish between two types of death-penalty supporters: those who would use the ultimate punishment for most or all murders and those who would use it only for the most aggravated murders.</p>
<p>The second survey had a more complex design. While it was also implemented by YouGov, it was a separate sample from the 2019 survey.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> The respondents were divided into four groups of equal size. The first two groups were asked to list everything that comes to mind when they think about the debate over the death penalty in the United States. Half of these individuals were then asked the standard Gallup question measuring death-penalty support, and half were asked the same question we posed in our 2019 survey. The third group was asked first to list what comes to mind when they think of murder victims and their families, and then they were asked the same death-penalty support question as in our 2019 survey. The fourth group was asked to list what comes to mind when they think about the possibility of an innocent person being executed, and then they were asked the same death-penalty support question as in our 2019 survey. The purpose of this design was to test whether “framing” the debate in a certain way (the third and fourth groups) would affect the results. As the project’s future publications will demonstrate, the framing had a very small effect on our measurements of death-penalty support, and (as expected) our question yielded higher levels of support than the Gallup question. This report describes some of the key findings of the two surveys, using the second group (the control group) of respondents from the 2020 survey. This group had the most directly comparable survey to those who took our 2019 survey. As we detail here, the results of the 2020 survey were quite similar to those from the 2019 survey.</p>
</section>
<section id="general-support-for-the-death-penalty" class="level2">
<h2 class="anchored" data-anchor-id="general-support-for-the-death-penalty">General support for the death penalty</h2>
<p>Table 1 presents the results of the two surveys on general support for the death penalty.</p>
<p>By adding the first two rows for each survey, we see that large majorities supported the death penalty for at least some types of murder. For those who responded to this question in 2019, fully three-fourths — 76% — voiced support. In the 2020 survey, the figure was 72%. Both of these figures are much higher than the 55-60% measured by Gallup and Pew (and most other polling organizations) using the generic question. Because 8% of those surveyed in 2019 did not answer the death-penalty questions, we cannot know their position on capital punishment. Yet even if 3 How Many Americans Support the Death Penalty? roseinstitute.org all of them opposed the death penalty for most or all types of murder (which, of course, is quite unlikely), we would still have 70% favoring the death penalty for at least some murders.</p>
<section id="table-1.-support-for-the-death-penalty-for-murder" class="level4">
<h4 class="anchored" data-anchor-id="table-1.-support-for-the-death-penalty-for-murder">Table 1. Support for the death penalty for murder</h4>
<table class="styled-table">
<thead>
<tr>
<th rowspan="2">
Category
</th>
<th colspan="2">
June 2019
</th>
<th colspan="2">
October 2020
</th>
</tr>
<tr>
<th>
Respondents only
</th>
<th>
Including non-respondents
</th>
<th>
Respondents only
</th>
<th>
Including non-respondents
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<strong>Support for most or all types of murder</strong>
</td>
<td>
38%
</td>
<td>
35%
</td>
<td>
32%
</td>
<td>
32%
</td>
</tr>
<tr>
<td>
<strong>Support only for the most aggravated murders</strong>
</td>
<td>
38%
</td>
<td>
35%
</td>
<td>
40%
</td>
<td>
40%
</td>
</tr>
<tr>
<td>
<strong>Oppose for most or all types of murder</strong>
</td>
<td>
24%
</td>
<td>
22%
</td>
<td>
28%
</td>
<td>
28%
</td>
</tr>
<tr>
<td>
<strong>Did not answer death penalty questions</strong>
</td>
<td>
—
</td>
<td>
8%
</td>
<td>
—
</td>
<td>
&lt;1%
</td>
</tr>
<tr>
<td>
<strong>Number (unweighted)</strong>
</td>
<td>
4,688
</td>
<td>
5,068
</td>
<td>
1,153
</td>
<td>
1,154
</td>
</tr>
<tr>
<td>
<strong>Survey margin of error</strong>
</td>
<td>
2.0%
</td>
<td>
2.0%
</td>
<td>
3.9%
</td>
<td>
3.9%
</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="impact-of-political-and-demographic-characteristics" class="level2">
<h2 class="anchored" data-anchor-id="impact-of-political-and-demographic-characteristics">Impact of political and demographic characteristics</h2>
<p>The 2019 survey contained information on a variety of political and demographic characteristics of the respondents. The 2020 survey asked many similar questions and collected similar information about the respondents. The results were broadly consistent across the two surveys.</p>
<p>The relationship of the respondents’ personal characteristics to their positions on the death penalty is presented in Tables 2-5. In all the following tables, the percentages for 2019 are based on the 4,688 respondents who answered the death penalty questions, and the percentages for 2020 are based on the 1,153 respondents — one-quarter of the entire sample — who were not part of the framing experiment and who were given the same three-part option for indicating their position on the death penalty as in the 2019 survey. Note that all the percentages are based on weighted data, using weights provided by YouGov, which take into account respondent gender, age, race, education, and region (from the Census Bureau’s American Community Survey) and 2016 presidential vote.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<p>Unsurprisingly, Table 2 shows a very strong association between support for the death penalty and the two political variables: party identification and political ideology. What is equally interesting is the level of support within each category. In both surveys, about nine-tenths of Republicans<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> recorded support for the death penalty for at least some types of murder (the total of the first two columns for each survey): 91% in 2019 and 89% in 2020. The figures for Democrats were considerably lower, though still a clear majority: 62% in 2019 and 57% in 2020. The relationship to political ideology was even more pronounced. Among those who considered themselves “very conservative,” 91% supported the death penalty in 2019 and 89% in 2020. This compares to 43% of “very liberals” in 2019 and 44% in 2020. Death-penalty support for “conservatives,” “moderates,” and “liberals” fell in rank-order between these extremes. Note, however, that of all the categories in Table 2 only “very liberals” had more opponents than supporters of the death penalty, and that even a substantial proportion of very liberal respondents favored it. Every other category had a majority in favor, even “liberals” – at 63% in 2019 and 60% in 2020. As we will see, none of the other personal characteristics made nearly as much a difference to support for capital punishment.</p>
<section id="table-2.-support-for-the-death-penalty-party-and-ideology" class="level4">
<h4 class="anchored" data-anchor-id="table-2.-support-for-the-death-penalty-party-and-ideology">Table 2. Support for the death penalty: Party and Ideology</h4>
<table class="styled-table">
<thead>
<tr>
<th rowspan="2">
Category
</th>
<th colspan="3">
June 2019
</th>
<th colspan="3">
October 2020
</th>
</tr>
<tr>
<th>
Support for most or all types of murder
</th>
<th>
Support only for the most aggravated murders
</th>
<th>
Oppose for most or all types of murder
</th>
<th>
Support for most or all types of murder
</th>
<th>
Support only for the most aggravated murders
</th>
<th>
Oppose for most or all types of murder
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<strong>All respondents</strong>
</td>
<td>
38%
</td>
<td>
38%
</td>
<td>
24%
</td>
<td>
32%
</td>
<td>
40%
</td>
<td>
28%
</td>
</tr>
<tr>
<td>
<strong>Party ID</strong>
</td>
<td colspan="6">
</td>
</tr>
<tr>
<td>
Democrat
</td>
<td>
21%
</td>
<td>
41%
</td>
<td>
38%
</td>
<td>
19%
</td>
<td>
38%
</td>
<td>
43%
</td>
</tr>
<tr>
<td>
Independent
</td>
<td>
38%
</td>
<td>
39%
</td>
<td>
23%
</td>
<td>
29%
</td>
<td>
47%
</td>
<td>
24%
</td>
</tr>
<tr>
<td>
Republican
</td>
<td>
56%
</td>
<td>
35%
</td>
<td>
9%
</td>
<td>
47%
</td>
<td>
42%
</td>
<td>
11%
</td>
</tr>
<tr>
<td>
<strong>Political ideology</strong>
</td>
<td colspan="6">
</td>
</tr>
<tr>
<td>
Very liberal
</td>
<td>
14%
</td>
<td>
29%
</td>
<td>
56%
</td>
<td>
17%
</td>
<td>
27%
</td>
<td>
56%
</td>
</tr>
<tr>
<td>
Liberal
</td>
<td>
19%
</td>
<td>
44%
</td>
<td>
37%
</td>
<td>
23%
</td>
<td>
37%
</td>
<td>
40%
</td>
</tr>
<tr>
<td>
Moderate
</td>
<td>
35%
</td>
<td>
44%
</td>
<td>
22%
</td>
<td>
27%
</td>
<td>
45%
</td>
<td>
28%
</td>
</tr>
<tr>
<td>
Conservative
</td>
<td>
52%
</td>
<td>
38%
</td>
<td>
10%
</td>
<td>
43%
</td>
<td>
46%
</td>
<td>
11%
</td>
</tr>
<tr>
<td>
Very conservative
</td>
<td>
65%
</td>
<td>
26%
</td>
<td>
9%
</td>
<td>
51%
</td>
<td>
38%
</td>
<td>
11%
</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="section" class="level1">
<h1></h1>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Gallup, “U.S. Support for Death Penalty Holds Above Majority Level,” Nov.&nbsp;19, 2020, at <a href="https://news.gallup.com/poll/325568/support-death-penalty-holds-above-majority-level.aspx" class="uri">https://news.gallup.com/poll/325568/support-death-penalty-holds-above-majority-level.aspx</a>. Pew Research Center, “Most Americans Favor the Death Penalty Despite Concerns About Its Administration,” June 2, 2021, at &lt;https://www.pewresearch. org/politics/2021/06/02/most-americans-favor-the-death-penalty-despiteconcerns-about-its-administration/?utm_source=AdaptiveMailer&amp;utm_medium=email&amp;utm_campaign=21-06-02%20Death%20Penalty%20GEN%20DISTRO&amp;org=982&amp;lvl=100&amp;ite=8618&amp;lea=1852192&amp;ctr=0&amp;par=1&amp;trk=&gt;.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This observation is not original to our research. See, among others, Baumgartner, Frank R., Marty Davidson, Kaneesha R. Johnson, Arvind Krishnamurthy, and Colin P. Wilson, Deadly Justice: A Statistical Portrait of the Death Penalty (New York: Oxford University Press, 2018), pp.&nbsp;267-269. Virginia became the twenty-third state to abolish the death penalty in February of 2021.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The last such survey we have found was conducted by the Associated Press in 1985 and asked about six aggravated murders: “Murder especially brutal”; “Murder for hire”; “Victim is child”; “Victim is police officer”; “Victim is prison guard”; “Convicted of killing more than one.” See Philip W. Harris, “Over-Simplification and Error in Public Opinion Surveys on Capital Punishment,” Justice Quarterly, Vol. 3, No.&nbsp;4 (December, 1986), Table 3, p.&nbsp;446. For public opinion on the proper punishment for school shooters, including both those who only injure their victims and those who kill them, see Schutten et al., “Punishing Rampage: Public Opinion on Sanctions for School Shooters,” Justice Quarterly, December 2019.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Although many reputable and widely publicized surveys (including those published and analyzed in peer-reviewed social science journals) use voter registration lists to identify participants, there is always the possibility that the views of registered voters (67% of all American citizens of voting age in 2018, according to the Census Bureau) may differ from the views of those who do not register to vote. In 2018, the Pew Research Center (which has now moved most of its polling online), conducted a major study that compared Americans’ opinions on a variety of issues when derived from two kinds of samples: one based on random digit dialing (which would include those not registered to vote) and another based on voter files. Pew found that for 56 of the 65 different questions, the results were “statistically indistinguishable.” This included the question on the death penalty. See Pew Research Center, “Comparing Survey Sampling Strategies: Random-Digit Dial vs.&nbsp;Voter Files,” October 9, 2018, at &lt;https://www. pewresearch.org/methods/2018/10/09/comparing-survey-sampling-strategies-random-digit-dialvs-voter-files/&gt;. PDF of full report at <a href="https://www.pewresearch.org/methods/wp-content/uploads/sites/10/2018/10/REPORT-Comparing-RDD-and-RBS-Surveys-Final-05.06.19-2.pdf." class="uri">https://www.pewresearch.org/methods/wp-content/uploads/sites/10/2018/10/REPORT-Comparing-RDD-and-RBS-Surveys-Final-05.06.19-2.pdf.</a><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>About 5.5% of the respondents (before weighting) in the 2020 survey had also been in the 2019 survey.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>For a very readable explanation on why YouGov uses past presidential vote, see: Rivers, Doug, “Pew Research: YouGov consistently outperforms competitors on accuracy,” May 13. 2016, at <a href="https://tinyurl.com/dh9t1yu4" class="uri">https://tinyurl.com/dh9t1yu4</a>.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>For personal party identification, respondents who report being “independent” but that “lean” towards the Republican or Democratic Party are treated as partisans of that party. See Keith, Bruce E., David B. Magleby, Candice J. Nelson, Elizabeth A. Orr, Mark C. Westlye, and Raymond Wolfinger, The Myth of the Independent Voter (University of California Press, 1992).<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>