<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Joseph M. Bessette">
<meta name="author" content="J. Andrew Sinclair">
<meta name="dcterms.date" content="2022-12-14">

<title>How Many Americans Support the Death Penalty? – Data Hub</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Data Hub</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./reportDraft.html" aria-current="page"> 
<span class="menu-text">Bessett-Sinclair Report</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Quarto Resource.html"> 
<span class="menu-text">Quarto Resources</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./hubstart.html"> 
<span class="menu-text">Data Hub</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./nets_project.html"> 
<span class="menu-text">NETS Project</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">How Many Americans Support the Death Penalty?</h1>
            <p class="subtitle lead">Results of National Surveys in 2019 and 2020</p>
                      </div>
  </div>
    
  <div class="quarto-title-meta-author">
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-heading">Affiliation</div>
    
      <div class="quarto-title-meta-contents">
      <p class="author">Joseph M. Bessette </p>
    </div>
    <div class="quarto-title-meta-contents">
          <p class="affiliation">
              Claremont McKenna College
            </p>
        </div>
      <div class="quarto-title-meta-contents">
      <p class="author">J. Andrew Sinclair </p>
    </div>
    <div class="quarto-title-meta-contents">
          <p class="affiliation">
              Claremont McKenna College
            </p>
        </div>
    </div>

  <div class="quarto-title-meta">

        
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">December 14, 2022</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#survey-design" id="toc-survey-design" class="nav-link" data-scroll-target="#survey-design">Survey Design</a></li>
  <li><a href="#general-support-for-the-death-penalty" id="toc-general-support-for-the-death-penalty" class="nav-link" data-scroll-target="#general-support-for-the-death-penalty">General support for the death penalty</a></li>
  <li><a href="#impact-of-political-and-demographic-characteristics" id="toc-impact-of-political-and-demographic-characteristics" class="nav-link" data-scroll-target="#impact-of-political-and-demographic-characteristics">Impact of political and demographic characteristics</a></li>
  <li><a href="#specific-aggravated-murders" id="toc-specific-aggravated-murders" class="nav-link" data-scroll-target="#specific-aggravated-murders">Specific aggravated murders</a></li>
  <li><a href="#varying-measures-of-support-for-the-death-penalty" id="toc-varying-measures-of-support-for-the-death-penalty" class="nav-link" data-scroll-target="#varying-measures-of-support-for-the-death-penalty">Varying measures of support for the death penalty</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Do Americans favor the death penalty for the crime of murder? According to Gallup and the Pew Research Center, two major polling organizations that regularly ask Americans this question and whose findings are widely publicized, public support ranges between 55% (Gallup, September-October, 2020) and 60% (Pew, April 2021).<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> These findings are generally accepted as an accurate gauge of current public attitudes: a clear majority in favor of the death penalty for murder but well below the modern peak of 78-80% in the mid-1990s.</p>
<p>Both Gallup and Pew ask a very generic question. Gallup asks, “Are you in favor of the death penalty for a person convicted of murder?” Although Pew gives more options to measure level of support or opposition, its question is otherwise nearly identical: “Do you strongly favor, favor, oppose or strongly oppose the death penalty for persons convicted of murder?” Most other polling organizations that have measured public opinion in the United States on the death penalty in recent decades have asked essentially the same question. One problem is that these questions do not distinguish between most murders – or, what we might call the “typical” or ”average” murder — and the specific kinds of aggravated murders that make a killer eligible for the death penalty in the 27 American states with capital punishment.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> Someone, for example, might oppose the death penalty for most murders but support it for, say, raping and murdering a child, or killing people by setting off a bomb in a public place, or killing someone after intentionally torturing the victim. How should such a person respond when asked whether he or she favors the death penalty for “a person convicted of murder”? This person might answer “no” to the generic question — and thus be counted as a death penalty opponent — even though he or she would support executing some murderers. A second problem is that the question does not allow respondents to distinguish between an abstract preference for the death penalty in some circumstances and the retention or adoption of the death penalty as actual public policy. Someone who approves of the death penalty in principle might answer “no” to the generic question because they interpret the question as asking about whether their state should have the death penalty – a policy they might oppose because of concerns about cost, mistakes, or discrimination.</p>
<p>Although polling organizations occasionally ask Americans whether they support the death penalty for a particular offender — such as Timothy McVeigh, who killed 168 in the 1995 bombing of the federal building in Oklahoma City and who was executed in 2001 (Gallup reported that 81% approved) — we can find no record in the past three decades of a national survey that polled Americans on their support for the death penalty for a variety of specific types of aggravated murder.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> To fill this gap in our knowledge of American public opinion on capital punishment, we devised a series of questions on the death penalty that were included in two national surveys (on several distinct topics) of approximately 5000 registered voters. The surveys were conducted online by YouGov in June of 2019.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
</section>
<section id="survey-design" class="level2">
<h2 class="anchored" data-anchor-id="survey-design">Survey Design</h2>
<p>The first survey began the section on capital punishment by alerting respondents that we would be asking about the death penalty for “different kinds of aggravated murders,” indicating that they could skip these questions: 92% did not. We then asked whether the respondent “support[ed] the death penalty for the crime of murder” and gave three optional responses: 1. “I support the death penalty for most or all types of murder.” 2. “I support the death penalty only for the most aggravated murders.” 3. “I oppose the death penalty for most or all types of murder.”</p>
<p>In our view, these options rectified the deficiency in the Gallup/Pew generic question because they allowed us to distinguish between two types of death-penalty supporters: those who would use the ultimate punishment for most or all murders and those who would use it only for the most aggravated murders.</p>
<p>The second survey had a more complex design. While it was also implemented by YouGov, it was a separate sample from the 2019 survey.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> The respondents were divided into four groups of equal size. The first two groups were asked to list everything that comes to mind when they think about the debate over the death penalty in the United States. Half of these individuals were then asked the standard Gallup question measuring death-penalty support, and half were asked the same question we posed in our 2019 survey. The third group was asked first to list what comes to mind when they think of murder victims and their families, and then they were asked the same death-penalty support question as in our 2019 survey. The fourth group was asked to list what comes to mind when they think about the possibility of an innocent person being executed, and then they were asked the same death-penalty support question as in our 2019 survey. The purpose of this design was to test whether “framing” the debate in a certain way (the third and fourth groups) would affect the results. As the project’s future publications will demonstrate, the framing had a very small effect on our measurements of death-penalty support, and (as expected) our question yielded higher levels of support than the Gallup question. This report describes some of the key findings of the two surveys, using the second group (the control group) of respondents from the 2020 survey. This group had the most directly comparable survey to those who took our 2019 survey. As we detail here, the results of the 2020 survey were quite similar to those from the 2019 survey.</p>
</section>
<section id="general-support-for-the-death-penalty" class="level2">
<h2 class="anchored" data-anchor-id="general-support-for-the-death-penalty">General support for the death penalty</h2>
<p>Table 1 presents the results of the two surveys on general support for the death penalty.</p>
<p>By adding the first two rows for each survey, we see that large majorities supported the death penalty for at least some types of murder. For those who responded to this question in 2019, fully three-fourths — 76% — voiced support. In the 2020 survey, the figure was 72%. Both of these figures are much higher than the 55-60% measured by Gallup and Pew (and most other polling organizations) using the generic question. Because 8% of those surveyed in 2019 did not answer the death-penalty questions, we cannot know their position on capital punishment. Yet even if 3 How Many Americans Support the Death Penalty? roseinstitute.org all of them opposed the death penalty for most or all types of murder (which, of course, is quite unlikely), we would still have 70% favoring the death penalty for at least some murders.</p>
<section id="table-1.-support-for-the-death-penalty-for-murder" class="level4">
<h4 class="anchored" data-anchor-id="table-1.-support-for-the-death-penalty-for-murder">Table 1. Support for the death penalty for murder</h4>
<table id="surveyTable1" class="styled-table">
<thead>
<tr>
<th rowspan="2">
Category
</th>
<th colspan="2">
June 2019
</th>
<th colspan="2">
October 2020
</th>
</tr>
<tr>
<th>
Respondents only
</th>
<th>
Including non-respondents
</th>
<th>
Respondents only
</th>
<th>
Including non-respondents
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<strong>Support for most or all types of murder</strong>
</td>
<td>
38%
</td>
<td>
35%
</td>
<td>
32%
</td>
<td>
32%
</td>
</tr>
<tr>
<td>
<strong>Support only for the most aggravated murders</strong>
</td>
<td>
38%
</td>
<td>
35%
</td>
<td>
40%
</td>
<td>
40%
</td>
</tr>
<tr>
<td>
<strong>Oppose for most or all types of murder</strong>
</td>
<td>
24%
</td>
<td>
22%
</td>
<td>
28%
</td>
<td>
28%
</td>
</tr>
<tr>
<td>
<strong>Did not answer death penalty questions</strong>
</td>
<td>
—
</td>
<td>
8%
</td>
<td>
—
</td>
<td>
&lt;1%
</td>
</tr>
<tr>
<td>
<strong>Number (unweighted)</strong>
</td>
<td>
4,688
</td>
<td>
5,068
</td>
<td>
1,153
</td>
<td>
1,154
</td>
</tr>
<tr>
<td>
<strong>Survey margin of error</strong>
</td>
<td>
2.0%
</td>
<td>
2.0%
</td>
<td>
3.9%
</td>
<td>
3.9%
</td>
</tr>
</tbody>
</table>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script>
<script>
function downloadTableAsExcel(tableId, filename) {
    let table = document.getElementById(tableId);
    let wb = XLSX.utils.book_new();
    let ws = XLSX.utils.table_to_sheet(table);
    
    XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
    XLSX.writeFile(wb, filename);
}
</script>
<button onclick="downloadTableAsExcel('surveyTable1', 'SurveyData1.xlsx')">
Download Table 1
</button>
</section>
</section>
<section id="impact-of-political-and-demographic-characteristics" class="level2">
<h2 class="anchored" data-anchor-id="impact-of-political-and-demographic-characteristics">Impact of political and demographic characteristics</h2>
<p>The 2019 survey contained information on a variety of political and demographic characteristics of the respondents. The 2020 survey asked many similar questions and collected similar information about the respondents. The results were broadly consistent across the two surveys.</p>
<p>The relationship of the respondents’ personal characteristics to their positions on the death penalty is presented in Tables 2-5. In all the following tables, the percentages for 2019 are based on the 4,688 respondents who answered the death penalty questions, and the percentages for 2020 are based on the 1,153 respondents — one-quarter of the entire sample — who were not part of the framing experiment and who were given the same three-part option for indicating their position on the death penalty as in the 2019 survey. Note that all the percentages are based on weighted data, using weights provided by YouGov, which take into account respondent gender, age, race, education, and region (from the Census Bureau’s American Community Survey) and 2016 presidential vote.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<p>Unsurprisingly, Table 2 shows a very strong association between support for the death penalty and the two political variables: party identification and political ideology. What is equally interesting is the level of support within each category. In both surveys, about nine-tenths of Republicans<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> recorded support for the death penalty for at least some types of murder (the total of the first two columns for each survey): 91% in 2019 and 89% in 2020. The figures for Democrats were considerably lower, though still a clear majority: 62% in 2019 and 57% in 2020. The relationship to political ideology was even more pronounced. Among those who considered themselves “very conservative,” 91% supported the death penalty in 2019 and 89% in 2020. This compares to 43% of “very liberals” in 2019 and 44% in 2020. Death-penalty support for “conservatives,” “moderates,” and “liberals” fell in rank-order between these extremes. Note, however, that of all the categories in Table 2 only “very liberals” had more opponents than supporters of the death penalty, and that even a substantial proportion of very liberal respondents favored it. Every other category had a majority in favor, even “liberals” – at 63% in 2019 and 60% in 2020. As we will see, none of the other personal characteristics made nearly as much a difference to support for capital punishment.</p>
<section id="table-2.-support-for-the-death-penalty-party-and-ideology" class="level4">
<h4 class="anchored" data-anchor-id="table-2.-support-for-the-death-penalty-party-and-ideology">Table 2. Support for the death penalty: Party and Ideology</h4>
<table id="surveyTable2" class="styled-table">
<thead>
<tr>
<th rowspan="2">
Category
</th>
<th colspan="3">
June 2019
</th>
<th colspan="3">
October 2020
</th>
</tr>
<tr>
<th>
Support for most or all types of murder
</th>
<th>
Support only for the most aggravated murders
</th>
<th>
Oppose for most or all types of murder
</th>
<th>
Support for most or all types of murder
</th>
<th>
Support only for the most aggravated murders
</th>
<th>
Oppose for most or all types of murder
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<strong>All respondents</strong>
</td>
<td>
38%
</td>
<td>
38%
</td>
<td>
24%
</td>
<td>
32%
</td>
<td>
40%
</td>
<td>
28%
</td>
</tr>
<tr>
<td>
<strong>Party ID</strong>
</td>
<td colspan="6">
</td>
</tr>
<tr>
<td>
Democrat
</td>
<td>
21%
</td>
<td>
41%
</td>
<td>
38%
</td>
<td>
19%
</td>
<td>
38%
</td>
<td>
43%
</td>
</tr>
<tr>
<td>
Independent
</td>
<td>
38%
</td>
<td>
39%
</td>
<td>
23%
</td>
<td>
29%
</td>
<td>
47%
</td>
<td>
24%
</td>
</tr>
<tr>
<td>
Republican
</td>
<td>
56%
</td>
<td>
35%
</td>
<td>
9%
</td>
<td>
47%
</td>
<td>
42%
</td>
<td>
11%
</td>
</tr>
<tr>
<td>
<strong>Political ideology</strong>
</td>
<td colspan="6">
</td>
</tr>
<tr>
<td>
Very liberal
</td>
<td>
14%
</td>
<td>
29%
</td>
<td>
56%
</td>
<td>
17%
</td>
<td>
27%
</td>
<td>
56%
</td>
</tr>
<tr>
<td>
Liberal
</td>
<td>
19%
</td>
<td>
44%
</td>
<td>
37%
</td>
<td>
23%
</td>
<td>
37%
</td>
<td>
40%
</td>
</tr>
<tr>
<td>
Moderate
</td>
<td>
35%
</td>
<td>
44%
</td>
<td>
22%
</td>
<td>
27%
</td>
<td>
45%
</td>
<td>
28%
</td>
</tr>
<tr>
<td>
Conservative
</td>
<td>
52%
</td>
<td>
38%
</td>
<td>
10%
</td>
<td>
43%
</td>
<td>
46%
</td>
<td>
11%
</td>
</tr>
<tr>
<td>
Very conservative
</td>
<td>
65%
</td>
<td>
26%
</td>
<td>
9%
</td>
<td>
51%
</td>
<td>
38%
</td>
<td>
11%
</td>
</tr>
</tbody>
</table>
<button onclick="downloadTableAsExcel('surveyTable2', 'SurveyData2.xlsx')">
Download Table 2
</button>
<p><br> As Table 3 shows, in both surveys Christians indicated somewhat more support for the death penalty than did those with no religion. In 2019, 80% of Protestants and 82% of Catholics voiced support, compared to 67% of the non-religious. In 2020, 81% of Protestants and 72% of Catholics supported the death penalty, compared to 62% of those with no religion. These differences are particularly interesting since the American Catholic bishops as well as the leaders of many Protestant denominations in the United States oppose the death penalty. Our results suggest that for whatever reasons, a secular worldview seems to incline individuals to oppose the death penalty compared to a religious worldview, even despite the rejection of capital punishment by many Christian leaders. Still, as noted, clear majorities of the non-religious in both surveys supported the death penalty for at least some murders.</p>
<p>The table also shows that the higher the educational attainment of individuals, the less likely they are to support the death penalty. In both surveys about eight in ten of those with no more than a high-school education supported the death penalty: 83% in 2019 and 80% in 2020. For those with a post-graduate education, the figures are closer to six in ten: 62% in 2019 and 65% in 2020.</p>
</section>
<section id="table-3.-support-for-the-death-penalty-religion-and-education" class="level4">
<h4 class="anchored" data-anchor-id="table-3.-support-for-the-death-penalty-religion-and-education">Table 3. Support for the death penalty: Religion and Education</h4>
<table id="surveyTable3" class="styled-table">
<thead>
<tr>
<th rowspan="2">
Category
</th>
<th colspan="3">
June 2019
</th>
<th colspan="3">
October 2020
</th>
</tr>
<tr>
<th>
Support for most or all types of murder
</th>
<th>
Support only for the most aggravated murders
</th>
<th>
Oppose for most or all types of murder
</th>
<th>
Support for most or all types of murder
</th>
<th>
Support only for the most aggravated murders
</th>
<th>
Oppose for most or all types of murder
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<strong>All respondents</strong>
</td>
<td>
38%
</td>
<td>
38%
</td>
<td>
24%
</td>
<td>
32%
</td>
<td>
40%
</td>
<td>
28%
</td>
</tr>
<tr>
<td>
<strong>Religion</strong>
</td>
<td colspan="6">
</td>
</tr>
<tr>
<td>
Protestant
</td>
<td>
45%
</td>
<td>
35%
</td>
<td>
20%
</td>
<td>
39%
</td>
<td>
42%
</td>
<td>
20%
</td>
</tr>
<tr>
<td>
Catholic
</td>
<td>
39%
</td>
<td>
43%
</td>
<td>
17%
</td>
<td>
30%
</td>
<td>
42%
</td>
<td>
28%
</td>
</tr>
<tr>
<td>
Other religion
</td>
<td>
36%
</td>
<td>
37%
</td>
<td>
26%
</td>
<td>
36%
</td>
<td>
37%
</td>
<td>
28%
</td>
</tr>
<tr>
<td>
No religion
</td>
<td>
28%
</td>
<td>
39%
</td>
<td>
33%
</td>
<td>
23%
</td>
<td>
39%
</td>
<td>
38%
</td>
</tr>
<tr>
<td>
<strong>Education (highest level completed)</strong>
</td>
<td colspan="6">
</td>
</tr>
<tr>
<td>
HS or less
</td>
<td>
48%
</td>
<td>
35%
</td>
<td>
17%
</td>
<td>
43%
</td>
<td>
37%
</td>
<td>
20%
</td>
</tr>
<tr>
<td>
Some college
</td>
<td>
37%
</td>
<td>
40%
</td>
<td>
23%
</td>
<td>
30%
</td>
<td>
44%
</td>
<td>
26%
</td>
</tr>
<tr>
<td>
College graduate
</td>
<td>
31%
</td>
<td>
40%
</td>
<td>
29%
</td>
<td>
26%
</td>
<td>
39%
</td>
<td>
35%
</td>
</tr>
<tr>
<td>
Post-grad
</td>
<td>
26%
</td>
<td>
36%
</td>
<td>
38%
</td>
<td>
22%
</td>
<td>
43%
</td>
<td>
35%
</td>
</tr>
</tbody>
</table>
<button onclick="downloadTableAsExcel('surveyTable3', 'SurveyData3.xlsx')">
Download Table 3
</button>
<p><br> Table 4 examines three demographic characteristics: gender, race/ethnicity, and age. In 2019, men and women supported the death penalty at nearly identical levels: 77% for men and 74% for women. In 2020, the difference was more pronounced: 75% of men and 69% of women.</p>
<p>Large majorities of all three racial/ethnic groups for which we had data supported the death penalty for at least some murders. In 2019, the figures were 77% for whites, 69% for Blacks, and 76% for Hispanics. In 2020, 75% of whites voiced support of the death penalty, compared to 67% of Blacks. Hispanic support in 2020 (64%), however, was twelve percentage points lower than in 2019 (76%). In both surveys, whites were considerably more likely than the other two groups to support the death penalty “for most or all types of murder.” Conversely, in 2019 Blacks and Hispanics were more likely than whites to support the death penalty “only for the most aggravated murders.”</p>
</section>
<section id="table-4.-support-for-the-death-penalty-gender-raceethnicity-and-age-8" class="level4">
<h4 class="anchored" data-anchor-id="table-4.-support-for-the-death-penalty-gender-raceethnicity-and-age-8">Table 4. Support for the death penalty: Gender, Race/Ethnicity, and Age <a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></h4>
<table id="surveyTable4" class="styled-table">
<thead>
<tr>
<th rowspan="2">
Category
</th>
<th colspan="3">
June 2019
</th>
<th colspan="3">
October 2020
</th>
</tr>
<tr>
<th>
Support for most or all types of murder
</th>
<th>
Support only for the most aggravated murders
</th>
<th>
Oppose for most or all types of murder
</th>
<th>
Support for most or all types of murder
</th>
<th>
Support only for the most aggravated murders
</th>
<th>
Oppose for most or all types of murder
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<strong>All respondents</strong>
</td>
<td>
38%
</td>
<td>
38%
</td>
<td>
24%
</td>
<td>
32%
</td>
<td>
40%
</td>
<td>
28%
</td>
</tr>
<tr>
<td>
<strong>Gender</strong>
</td>
<td colspan="6">
</td>
</tr>
<tr>
<td>
Male
</td>
<td>
41%
</td>
<td>
36%
</td>
<td>
23%
</td>
<td>
37%
</td>
<td>
38%
</td>
<td>
25%
</td>
</tr>
<tr>
<td>
Female
</td>
<td>
35%
</td>
<td>
39%
</td>
<td>
25%
</td>
<td>
27%
</td>
<td>
42%
</td>
<td>
30%
</td>
</tr>
<tr>
<td>
<strong>Race/Ethnicity</strong>
</td>
<td colspan="6">
</td>
</tr>
<tr>
<td>
White (non-Hispanic)
</td>
<td>
41%
</td>
<td>
36%
</td>
<td>
23%
</td>
<td>
34%
</td>
<td>
41%
</td>
<td>
25%
</td>
</tr>
<tr>
<td>
Black (non-Hispanic)
</td>
<td>
25%
</td>
<td>
44%
</td>
<td>
31%
</td>
<td>
26%
</td>
<td>
41%
</td>
<td>
33%
</td>
</tr>
<tr>
<td>
Hispanic
</td>
<td>
31%
</td>
<td>
45%
</td>
<td>
24%
</td>
<td>
24%
</td>
<td>
42%
</td>
<td>
34%
</td>
</tr>
<tr>
<td>
Other
</td>
<td>
26%
</td>
<td>
47%
</td>
<td>
27%
</td>
<td>
23%
</td>
<td>
40%
</td>
<td>
36%
</td>
</tr>
<tr>
<td>
<strong>Age</strong>
</td>
<td colspan="6">
</td>
</tr>
<tr>
<td>
18-29
</td>
<td>
21%
</td>
<td>
39%
</td>
<td>
40%
</td>
<td>
11%
</td>
<td>
54%
</td>
<td>
36%
</td>
</tr>
<tr>
<td>
30-44
</td>
<td>
34%
</td>
<td>
42%
</td>
<td>
24%
</td>
<td>
32%
</td>
<td>
37%
</td>
<td>
32%
</td>
</tr>
<tr>
<td>
45-64
</td>
<td>
43%
</td>
<td>
37%
</td>
<td>
20%
</td>
<td>
37%
</td>
<td>
37%
</td>
<td>
23%
</td>
</tr>
<tr>
<td>
65 and older
</td>
<td>
43%
</td>
<td>
37%
</td>
<td>
20%
</td>
<td>
41%
</td>
<td>
41%
</td>
<td>
23%
</td>
</tr>
</tbody>
</table>
<button onclick="downloadTableAsExcel('surveyTable4', 'SurveyData4.xlsx')">
Download Table 4
</button>
<p><br> The survey results for both years showed that older respondents were considerably more likely to support the death penalty than were younger respondents. While a solid majority (60%) of those 18-29 supported the death penalty in 2019, the figures for both those 45-64 and those 65 and older were 80%. For the sample in the 2020 survey, the difference was not quite as great: 65% for the youngest group, versus 74% and 77% for the two oldest groups. While the overall support for the death penalty among the youngest respondents was 5 percentage points higher in the 2020 survey, their support for the death penalty “for most or all types of murder” was lower: 11% instead of 21%. This drop was more than offset by a large increase in support for the death penalty “only for the most aggravated murders”: from 39% to 54%.</p>
<p>As Table 5 shows, region made little difference to death penalty support in the 2019 survey, with support in all four regions ranging between 73% in the West and 79% in the South. Regional differences were somewhat more pronounced in 2020, with residents of the Northeast recording a low of 64% in favor and those of the South recording a high of 76%. Despite these small regional differences, a substantial majority of all executions in the modern era have occurred in the South, and it is the only region in which every state had the death penalty during the period of our two surveys.</p>
</section>
<section id="table-5.-support-for-the-death-penalty-residence" class="level4">
<h4 class="anchored" data-anchor-id="table-5.-support-for-the-death-penalty-residence">Table 5. Support for the death penalty: Residence</h4>
<table id="surveyTable5" class="styled-table">
<thead>
<tr>
<th rowspan="2">
Category
</th>
<th colspan="3">
June 2019
</th>
<th colspan="3">
October 2020
</th>
</tr>
<tr>
<th>
Support for most or all types of murder
</th>
<th>
Support only for the most aggravated murders
</th>
<th>
Oppose for most or all types of murder
</th>
<th>
Support for most or all types of murder
</th>
<th>
Support only for the most aggravated murders
</th>
<th>
Oppose for most or all types of murder
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<strong>Region</strong>
</td>
<td colspan="6">
</td>
</tr>
<tr>
<td>
Northeast
</td>
<td>
39%
</td>
<td>
35%
</td>
<td>
27%
</td>
<td>
27%
</td>
<td>
37%
</td>
<td>
37%
</td>
</tr>
<tr>
<td>
Midwest
</td>
<td>
36%
</td>
<td>
39%
</td>
<td>
25%
</td>
<td>
26%
</td>
<td>
49%
</td>
<td>
25%
</td>
</tr>
<tr>
<td>
South
</td>
<td>
39%
</td>
<td>
40%
</td>
<td>
21%
</td>
<td>
36%
</td>
<td>
40%
</td>
<td>
23%
</td>
</tr>
<tr>
<td>
West
</td>
<td>
37%
</td>
<td>
36%
</td>
<td>
27%
</td>
<td>
33%
</td>
<td>
35%
</td>
<td>
31%
</td>
</tr>
<tr>
<td>
<strong>Urban/Rural (Congressional District)</strong>
</td>
<td colspan="6">
</td>
</tr>
<tr>
<td>
Under 2% rural
</td>
<td>
31%
</td>
<td>
37%
</td>
<td>
33%
</td>
<td>
—
</td>
<td>
—
</td>
<td>
—
</td>
</tr>
<tr>
<td>
2-35% rural
</td>
<td>
38%
</td>
<td>
39%
</td>
<td>
22%
</td>
<td>
—
</td>
<td>
—
</td>
<td>
—
</td>
</tr>
<tr>
<td>
Above 35% rural
</td>
<td>
45%
</td>
<td>
36%
</td>
<td>
20%
</td>
<td>
—
</td>
<td>
—
</td>
<td>
—
</td>
</tr>
</tbody>
</table>
<button onclick="downloadTableAsExcel('surveyTable5', 'SurveyData5.xlsx')">
Download Table 5
</button>
<p><br> For the 2019 survey, we were also able to examine the urban/rural nature of the congressional districts in which the respondents lived. Although 68% of respondents in the most urban districts favored the death penalty for at least some murders, that number rose to 81% in the most rural districts. Conversely, a third (33%) of residents of the most urban districts opposed the death penalty “for most or all types of murder,” compared to only one-fifth (20%) of those living in the most rural districts.</p>
<p>As Tables 2-5, show, there are larger differences across some types of personal characteristics than others. The differences are particularly noticeable for ideology, party, education, and age. There is, of course, overlap among the types of personal characteristics: liberals, for example, are more likely to be Democrats than Republicans and, conversely, conservatives are more likely to be Republicans than Democrats. In our ongoing research, we explore the independent effect of these variables (to be presented in future publications). Yet, the direction of the relationships shown in Tables 2-5 should not be surprising (for example, that conservatives are more likely to favor the death penalty).</p>
<p>What may be more surprising is the level of support for the death penalty, for at least some aggravated murders, in categories that are frequently presumed to oppose it. For example, even among very liberal respondents, 43% in 2019 and 44% in 2020 expressed some support for the death penalty. Nor is this all. As we illustrate in the next section, when asked about specific types of murders, many of the respondents who indicated opposition on the first question then selected at least one type of murder as appropriate for the death penalty.</p>
</section>
</section>
<section id="specific-aggravated-murders" class="level2">
<h2 class="anchored" data-anchor-id="specific-aggravated-murders">Specific aggravated murders</h2>
<p>After asking the general support question in the 2019 survey, we sought to identify the types of aggravated murder for which the respondents believed the death penalty was appropriate. Outside the context of any specific murder case, we presented a list of fifteen types of murder that are commonly specified in state death penalty statutes and/or frequently show up among those sentenced to death, and we asked whether the respondent supported the death penalty for any of these. Because we asked other new death-penalty questions in the 2020 survey, we did not present the respondents with the full list of fifteen aggravated murders. Instead, we chose three from the 2019 survey – raping and murdering a child, killing dozens of people as part of a terrorist attack, and killing someone to rob him or her — and two others that are not normally eligible for the death penalty – killing multiple people while drunk driving and a gang member killing a rival gang-member.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> The results from the two surveys are in Table 6.</p>
<section id="table-6.-support-for-the-death-penalty-for-specific-types-of-murder-ranked-by-level-of-support-in-201910" class="level4">
<h4 class="anchored" data-anchor-id="table-6.-support-for-the-death-penalty-for-specific-types-of-murder-ranked-by-level-of-support-in-201910">Table 6. Support for the death penalty for specific types of murder (ranked by level of support in 2019)<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></h4>
<table id="surveyTable6" class="styled-table">
<thead>
<tr>
<th>
</th>
<th>
June 2019
</th>
<th>
October 2020
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Selected at least one aggravated murder
</td>
<td>
86%
</td>
<td>
80%
</td>
</tr>
<tr>
<td>
<ol type="1">
<li>Raping and murdering a child
</li></ol></td>
<td>
80%
</td>
<td>
74%
</td>
</tr>
<tr>
<td>
<ol start="2" type="1">
<li>Kidnapping and murdering a child
</li></ol></td>
<td>
75%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
<ol start="3" type="1">
<li>Killing dozens of people as part of a terrorist attack
</li></ol></td>
<td>
75%
</td>
<td>
74%
</td>
</tr>
<tr>
<td>
<ol start="4" type="1">
<li>Killing someone after intentionally torturing him or her
</li></ol></td>
<td>
73%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
<ol start="5" type="1">
<li>Killing one or more persons by setting off a bomb in a public place
</li></ol></td>
<td>
70%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
<ol start="6" type="1">
<li>Raping and murdering an adult
</li></ol></td>
<td>
69%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
<ol start="7" type="1">
<li>Kidnapping and murdering an adult
</li></ol></td>
<td>
65%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
<ol start="8" type="1">
<li>Killing three or more persons in the same incident
</li></ol></td>
<td>
62%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
<ol start="9" type="1">
<li>Killing a witness to a crime to prevent his or her testimony
</li></ol></td>
<td>
61%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
<ol start="10" type="1">
<li>Killing two or more persons in the same incident
</li></ol></td>
<td>
60%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
<ol start="11" type="1">
<li>Killing a law enforcement officer engaged in his or her official duties
</li></ol></td>
<td>
57%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
<ol start="12" type="1">
<li>Killing someone because paid to do so by another person
</li></ol></td>
<td>
55%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
<ol start="13" type="1">
<li>Killing a prison guard (by an inmate)
</li></ol></td>
<td>
53%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
<ol start="14" type="1">
<li>Killing someone after breaking into their home
</li></ol></td>
<td>
52%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
15a. Killing someone during the course of a robbery
</td>
<td>
49%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
15b. Killing someone to rob him or her
</td>
<td>
—
</td>
<td>
48%
</td>
</tr>
<tr>
<td>
<ol start="16" type="1">
<li>Murder of a gang member by a rival gang-member
</li></ol></td>
<td>
—
</td>
<td>
34%
</td>
</tr>
<tr>
<td>
<ol start="17" type="1">
<li>Killing multiple people while drunk driving
</li></ol></td>
<td>
—
</td>
<td>
26%
</td>
</tr>
<tr>
<td>
Number of respondents (unweighted)
</td>
<td>
4.706
</td>
<td>
1,154
</td>
</tr>
</tbody>
</table>
<button onclick="downloadTableAsExcel('surveyTable6', 'SurveyData6.xlsx')">
Download Table 6
</button>
<br> <br> As the table shows, 10 of the 15 murder types included in the 2019 survey garnered at least 60% support, five at least 70%, and one – raping and murdering a child — 80%. Altogether, 86% of respondents selected at least one aggravated murder. This 86% figure is ten percentage points higher than the 76% registered by our general support question (Table 1). This is because, as Table 7 shows, a substantial number of those who said that they “oppose the death penalty for most or all types of murder” (24% of all the respondents) actually supported the death penalty for one or more of the fifteen aggravated murders (11% of the respondents). Put another way, 46% of those who looked like opponents of the death penalty in their answer to the initial threepart question chose at least one type of murder as meriting a death sentence. It appears, then, that only 13% of the respondents in 2019 would oppose using the death penalty for any murder, no matter how aggravated. (This result is broadly consistent with Gallup’s finding in 2001 that many Americans who normally oppose the death penalty supported it for Timothy McVeigh.)
















</section>
<section id="table-7.-comparing-general-death-penalty-support-and-selection-of-specific-types-of-murder" class="level4">
<h4 class="anchored" data-anchor-id="table-7.-comparing-general-death-penalty-support-and-selection-of-specific-types-of-murder">Table 7. Comparing general death penalty support and selection of specific types of murder</h4>
<table id="surveyTable7" class="styled-table">
<thead>
<tr>
<th rowspan="2">
Selected:
</th>
<th colspan="3">
June 2019
</th>
<th colspan="3">
October 2020
</th>
</tr>
<tr>
<th>
Support for most or all types of murder
</th>
<th>
Support only for the most aggravated murders
</th>
<th>
Oppose for most or all types of murder
</th>
<th>
Support for most or all types of murder
</th>
<th>
Support only for the most aggravated murders
</th>
<th>
Oppose for most or all types of murder
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<strong>One or more specific types of murder</strong>
</td>
<td>
38%
</td>
<td>
38%
</td>
<td>
11%
</td>
<td>
31%
</td>
<td>
40%
</td>
<td>
9%
</td>
</tr>
<tr>
<td>
<strong>No murders</strong>
</td>
<td>
0%
</td>
<td>
0%
</td>
<td>
13%
</td>
<td>
1%
</td>
<td>
1%
</td>
<td>
18%
</td>
</tr>
<tr>
<td colspan="7">
<strong>Number (unweighted):</strong> 4,688 in 2019; 1,153 in 2020.
</td>
</tr>
<tr>
<td colspan="7">
<em>Note: All percentages are cell percentages based on weighted data. For each survey, cell percentages add to 100%.</em>
</td>
</tr>
</tbody>
</table>
<button onclick="downloadTableAsExcel('surveyTable7', 'SurveyData7.xlsx')">
Download Table 7
</button>
<p><br> Comparing the 2019 and 2020 survey responses, we got nearly identical results for the terrorist attack (75% and 74%) and the robbery murder (49% and 48%). Slightly fewer respondents chose raping and murdering a child in 2020 (74%) than in 2019 (80%). Overall, 80% of the respondents in the second survey chose at least one of the five types of killing, compared to 86% in 2019 when we had a much longer list from which to choose (and, importantly, some respondents had opted-out of the death penalty questions in 2019). In the 2020 survey, a third of those who said they opposed the death penalty “for most or all types of murder” chose at least one of the five types of killings we listed.</p>
</section>
</section>
<section id="varying-measures-of-support-for-the-death-penalty" class="level2">
<h2 class="anchored" data-anchor-id="varying-measures-of-support-for-the-death-penalty">Varying measures of support for the death penalty</h2>
<p>As the results presented here demonstrate, the standard surveys of American public opinion on capital punishment substantially understate the number of Americans who support the death penalty – in at least one sense. Instead of the commonly reported figures of 55-60%, we find that simply distinguishing between “most or all types of murder” and “the most aggravated murders” shows that approximately three-fourths of American voters (76% in 2019 and 72% in 2020) support capital punishment for at least some types of murder. And when respondents are able to choose from a list of specific types of aggravated murder, support rises to eight in ten Americans (80% in our 2020 survey) or even more (86% with our 2019 approach).</p>
<p>While researchers have long known that different survey questions can produce substantially different estimates of support across a host of policy issues, a full exploration of those differences can help us better understand opinion on important policy questions. We are not asserting that our measures are the only reasonable estimate of support for the death penalty, or that lower estimates on different questions are not also informative. Instead, our results on our two key questions qualify those other estimates; for in our data, even a substantial proportion of respondents who say on the first question that they oppose the death penalty “for most or all types of murder” subsequently chose one or more aggravated murders as meriting execution. Using multiple measures helps us better understand what voters mean when they voice support or opposition to capital punishment. It opens up a line of inquiry: if so many people support the death penalty in principle for certain types of crimes, why are all estimates of support for the death penalty not equally as high?</p>
<p>Our ongoing research addresses this issue. In addition to asking questions about the reasons why voters support or oppose the death penalty, and questions about other related policy views and personal characteristics, we also asked specific death-penalty policy questions on both the 2019 and 2020 surveys. In general, these results show a substantial gap between the estimate of more theoretical death penalty approval (obtained with our general question and specific crimes question) and more policy-oriented questions. Unlike comparing between surveys, where differences between samples or methodology could explain different estimates, these are questions asked of the same individuals within the same survey</p>
<p>In 2019, we asked a state oversample in California about Governor Gavin Newsom’s moratorium on carrying out the death penalty, which he announced in March of 2019. We had 1,151 respondents from California, of whom 1,061 answered the death penalty questions. Weighted to California’s characteristics, 70% supported the death penalty for some or most murders on the first question and 82% supported the death penalty for at least one of the crimes on our list. Yet only 51% disapproved of Newsom’s moratorium on the death penalty. In our oversample of residents of California in our 2020 survey, 57% said they would retain or adopt the death penalty in their state.</p>
<p>In New York in the 2019 survey, we had 1,066 respondents, of whom 971 answered the death penalty questions. When weighted to New York’s characteristics, 72% favored the death on the first question and 85% selected at least one specific crime. When we asked whether the death penalty should be reinstated “for certain aggravated murders,” 66% agreed. In the 2020 oversample of New York residents, 54% said they would adopt or retain the death penalty in their state.</p>
<p>As noted above, in 2020 we found that among the 1,154 respondents in the national control group, 72% supported the death penalty on the first question and 80% selected at least one specific crime. We also asked a general question that could apply in both death penalty and abolition states – inquiring whether the respondent wished to either retain or adopt the death penalty in their state: 60% of the respondents in that same control group said they did. These varying results from the national sample, California, and New York are summarized in Table 8.</p>
<section id="table-8.-varying-measures-of-death-penalty-support-2019-and-2020-surveys" class="level4">
<h4 class="anchored" data-anchor-id="table-8.-varying-measures-of-death-penalty-support-2019-and-2020-surveys">Table 8. Varying measures of death penalty support: 2019 and 2020 surveys</h4>
<table id="surveyTable8" class="styled-table">
<thead>
<tr>
<th rowspan="2">
</th>
<th>
June 2019
</th>
<th>
October 2020
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<strong>National sample</strong>
</td>
<td colspan="2">
</td>
</tr>
<tr>
<td>
Supported the death penalty either “for most or all types of murder” or “only for the most aggravated murders”
</td>
<td>
76%
</td>
<td>
72%
</td>
</tr>
<tr>
<td>
Chose a specific aggravated murder as meriting the death penalty
</td>
<td>
86%
</td>
<td>
80%
</td>
</tr>
<tr>
<td>
Supported retaining or adopting the death penalty in their state
</td>
<td>
—
</td>
<td>
60%
</td>
</tr>
<tr>
<td>
<strong>California sample</strong>
</td>
<td colspan="2">
</td>
</tr>
<tr>
<td>
Supported the death penalty either “for most or all types of murder” or “only for the most aggravated murders”
</td>
<td>
70%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
Chose a specific aggravated murder as meriting the death penalty
</td>
<td>
82%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
Disapproved of CA Governor Gavin Newsom’s moratorium on carrying out the death penalty
</td>
<td>
51%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
Supported retaining or adopting the death penalty in their state
</td>
<td>
—
</td>
<td>
57%
</td>
</tr>
<tr>
<td>
<strong>New York sample</strong>
</td>
<td colspan="2">
</td>
</tr>
<tr>
<td>
Supported the death penalty either “for most or all types of murder” or “only for the most aggravated murders”
</td>
<td>
72%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
Chose a specific aggravated murder as meriting the death penalty
</td>
<td>
85%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
Supported New York reinstating the death penalty “for certain aggravated murders”
</td>
<td>
66%
</td>
<td>
—
</td>
</tr>
<tr>
<td>
Supported retaining or adopting the death penalty in their state
</td>
<td>
—
</td>
<td>
54%
</td>
</tr>
<tr>
<td colspan="3">
<em>There were too few residents of California and New York in the October 2020 control group to produce meaningful numbers for the questions on general death-penalty support and the selection of specific aggravated murders. For the questions on retaining or adopting the death penalty in their state, we used the entire California (788 respondents) and New York (666 respondents) oversamples from the 2020 survey, including those from other experimental groups. These estimates use state-specific weights.</em>
</td>
</tr>
</tbody>
</table>
<button onclick="downloadTableAsExcel('surveyTable8', 'SurveyData8.xlsx')">
Download Table 8
</button>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Our research is focused on better understanding how the public thinks about capital punishment, taking seriously the possibility that the different answers across different types of questions can convey meaningful information about what Americans believe, and not just voter confusion.</p>
<p>As Table 8 shows, American voters distinguish between support for the death penalty in principle and support the death penalty as public policy. Approximately a fifth of our respondents advocated the death penalty for at least some aggravated murders but then opposed their state retaining or adopting the death penalty. There are a number of possible reasons why this is so. Principled advocates of capital punishment might be put off by the cost of the system, the seemingly endless appeals, the failure of their state to actually use the punishment; or they may have concerns about mistakes or discrimination. Yet, it is also possible that our own generic question about “retain[ing]” or “adopt[ing]” the death penalty in their state understates the potential level of public support for a law that, for example, focused on a few highly aggravated murders, streamlined the appeals process, and/or provided special safeguards against mistaken convictions.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></p>
<p>This gap between those who favor the death penalty in principle for at least some aggravated murders (about eight in ten) and those who support their state retaining or adopting the death penalty (about six in ten) represents a contested policy space. While the authors of this report disagree about whether capital punishment should be public policy in the United States, we agree that the standard type of death penalty question, asked over and over again for more than half a century, leaves policymakers, scholars, and citizens with an incomplete picture of support, or potential support, for the death penalty.</p>
</section>
<section id="section" class="level1">
<h1></h1>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Gallup, “U.S. Support for Death Penalty Holds Above Majority Level,” Nov.&nbsp;19, 2020, at <a href="https://news.gallup.com/poll/325568/support-death-penalty-holds-above-majority-level.aspx" class="uri">https://news.gallup.com/poll/325568/support-death-penalty-holds-above-majority-level.aspx</a>. Pew Research Center, “Most Americans Favor the Death Penalty Despite Concerns About Its Administration,” June 2, 2021, at &lt;https://www.pewresearch. org/politics/2021/06/02/most-americans-favor-the-death-penalty-despiteconcerns-about-its-administration/?utm_source=AdaptiveMailer&amp;utm_medium=email&amp;utm_campaign=21-06-02%20Death%20Penalty%20GEN%20DISTRO&amp;org=982&amp;lvl=100&amp;ite=8618&amp;lea=1852192&amp;ctr=0&amp;par=1&amp;trk=&gt;.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This observation is not original to our research. See, among others, Baumgartner, Frank R., Marty Davidson, Kaneesha R. Johnson, Arvind Krishnamurthy, and Colin P. Wilson, Deadly Justice: A Statistical Portrait of the Death Penalty (New York: Oxford University Press, 2018), pp.&nbsp;267-269. Virginia became the twenty-third state to abolish the death penalty in February of 2021.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The last such survey we have found was conducted by the Associated Press in 1985 and asked about six aggravated murders: “Murder especially brutal”; “Murder for hire”; “Victim is child”; “Victim is police officer”; “Victim is prison guard”; “Convicted of killing more than one.” See Philip W. Harris, “Over-Simplification and Error in Public Opinion Surveys on Capital Punishment,” Justice Quarterly, Vol. 3, No.&nbsp;4 (December, 1986), Table 3, p.&nbsp;446. For public opinion on the proper punishment for school shooters, including both those who only injure their victims and those who kill them, see Schutten et al., “Punishing Rampage: Public Opinion on Sanctions for School Shooters,” Justice Quarterly, December 2019.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Although many reputable and widely publicized surveys (including those published and analyzed in peer-reviewed social science journals) use voter registration lists to identify participants, there is always the possibility that the views of registered voters (67% of all American citizens of voting age in 2018, according to the Census Bureau) may differ from the views of those who do not register to vote. In 2018, the Pew Research Center (which has now moved most of its polling online), conducted a major study that compared Americans’ opinions on a variety of issues when derived from two kinds of samples: one based on random digit dialing (which would include those not registered to vote) and another based on voter files. Pew found that for 56 of the 65 different questions, the results were “statistically indistinguishable.” This included the question on the death penalty. See Pew Research Center, “Comparing Survey Sampling Strategies: Random-Digit Dial vs.&nbsp;Voter Files,” October 9, 2018, at &lt;https://www. pewresearch.org/methods/2018/10/09/comparing-survey-sampling-strategies-random-digit-dialvs-voter-files/&gt;. PDF of full report at <a href="https://www.pewresearch.org/methods/wp-content/uploads/sites/10/2018/10/REPORT-Comparing-RDD-and-RBS-Surveys-Final-05.06.19-2.pdf." class="uri">https://www.pewresearch.org/methods/wp-content/uploads/sites/10/2018/10/REPORT-Comparing-RDD-and-RBS-Surveys-Final-05.06.19-2.pdf.</a><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>About 5.5% of the respondents (before weighting) in the 2020 survey had also been in the 2019 survey.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>For a very readable explanation on why YouGov uses past presidential vote, see: Rivers, Doug, “Pew Research: YouGov consistently outperforms competitors on accuracy,” May 13. 2016, at <a href="https://tinyurl.com/dh9t1yu4" class="uri">https://tinyurl.com/dh9t1yu4</a>.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>For personal party identification, respondents who report being “independent” but that “lean” towards the Republican or Democratic Party are treated as partisans of that party. See Keith, Bruce E., David B. Magleby, Candice J. Nelson, Elizabeth A. Orr, Mark C. Westlye, and Raymond Wolfinger, The Myth of the Independent Voter (University of California Press, 1992).<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Race/ethnic categories come from the standard YouGov profile question, “What racial or ethnic group best describes you?” The full range of options is: White, Black, Hispanic, Asian, Native American, Two or more races, Other, Middle Eastern.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>In 2020, we slightly changed the wording of the robbery-murder question to eliminate the possibility that a respondent might think we were asking about a robbery victim killing the offender.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>Number of respondents (unweighted) differs slightly for the 2019 survey from the total N present in Table 1. There were 18 respondents who opted in to the death penalty questions, skipped the first question, and then had an opportunity to answer the specific murder questions. Those respondents are included in Table 6 but excluded from the calculation in Table 7 since they did not answer the original death penalty question. This has no meaningful impact on the results at all.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>For example, in November of 2016 a majority Californians voted in separate ballot propositions both to retain the death penalty (54%) and to speed up the process from sentence to execution (51%).<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>